### PR TITLE
Small tweaks to Upgrade Params and regulation.bin detection

### PR DESCRIPTION
**Pull request by ividyon**
Adjusted text of "Upgrade Params" option and loosened detection of regulation.bin file name.

Allows for selection like this:

2022-11-20_16-06-28__DSMapStudio

### CODE REVIEW

**Comment by Philiquaz** [comment]
Specific filename extension I'm not sure I agree with, seems to suit your purpose instead of general purpose.
However, extending the filters to include *.bin, or even just any file, would be a more general solution to how others may store their param files.

I like the additional hint for the loading of previous version, several people did slip up there.

**Comment by ividyon** [comment]
I was debating between *.bin and this, and thought this option would lead to less chafing. I'll gladly change it to *.bin.

**Comment by Philiquaz** [comment]
I would add another entry instead of changing the existing entry. People can choose to select anything, but they are initially prompted for the original filename

**Comment by ividyon** [comment]
> I would add another entry instead of changing the existing entry. People can choose to select anything, but they are initially prompted for the original filename

Done!

**Pull request merged**
