### PR TITLE
Settings Menu

### PR DESCRIPTION
**Pull request by vawser**
Restructured the Settings Menu to place things in a more consistent place. 
Added tooltips for most of the options, same as the ? tooltip used in the params.
Added configurable coloring for the wireframe primitives

image

### CODE REVIEW

**Comment by kingborehaha** [comment]
I'm not sure I'm too crazy about the diagonals with box primitives since it adds more visual noise, which we already have enough of already

**Comment by Philiquaz** [comment]
On the other hand, cleaning up the settings menu and adding explanations is kinda ideal.

**Comment by kingborehaha** [comment]
Yeah, for sure, I just wish it was not part of the same PR as the extra lines. Oh well, I suppose if it causes enough Foreseen Displeasure I can remove later (fat cat)

**Comment by vawser** [comment]
I've commented out the Map Grid stuff, the frustrum change and the additional lines in the box region.

**Pull request merged**
