### PR TITLE
Don't add string.empty at the start of param.

### PR DESCRIPTION
**Pull request by Nordgaren**
Fixes conflict with single entry params in old format that writes the param type in the param header.

### CODE REVIEW

**Comment by Nordgaren** [comment]
This could also be fixed in `FSParam/Param.cs` by changing line 649 to:
```cs
if (byteOffset != DetectedSize && byteOffset != DetectedSize - 2)
                throw new Exception($@"Row size paramdef mismatch for {ParamType}");
```

This might be good for anyone who has a param that wasn't being read due to the new string format.

**Comment by Nordgaren** [comment]
added 
```cs
if (byteOffset != DetectedSize && byteOffset != DetectedSize - 2)
                throw new Exception($@"Row size paramdef mismatch for {ParamType}");
                ```
                
                If anything can take out before merge. If someone has broken params due to this bug, opening and saving with this version will fix that.

**Comment by kingborehaha** [comment]
> added
> 
> ```cs
> if (byteOffset != DetectedSize && byteOffset != DetectedSize - 2)
>                 throw new Exception($@"Row size paramdef mismatch for {ParamType}");
> ```
> 
> If anything can take out before merge. If someone has broken params due to this bug, opening and saving with this version will fix that.

Bit worried about this part, since unrelated def mismatches could trigger it. I don't think there will be too many people with corrupted params who didn't revert immediately & start using an older verison of DSMS anyway.

**Comment by Nordgaren** [comment]
> > added
> > ```cs
> > if (byteOffset != DetectedSize && byteOffset != DetectedSize - 2)
> >                 throw new Exception($@"Row size paramdef mismatch for {ParamType}");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If anything can take out before merge. If someone has broken params due to this bug, opening and saving with this version will fix that.
> 
> Bit worried about this part, since unrelated def mismatches could trigger it. I don't think there will be too many people with corrupted params who didn't revert immediately & start using an older verison of DSMS anyway.

It would have to be a def that is off by 2. 

I could handle it in the specific case where this is wrong, which is when there's only one param row, but we are already guessing the param length by where the first string is, so we already risking param length mismatches, aren't we?

**Comment by Nordgaren** [comment]
Oh, well I am dumb, It seems they don't have any string offset in the header of these versions? I could have swore there was.

So it makes sense. Sad.

**Pull request merged**
