### PR TITLE
Add 0x100000 bytes to be extra sure we have enough buffer

### PR DESCRIPTION
**Pull request by Shadowth117**

### CODE REVIEW

**Comment by Shadowth117** [comment]
A note on this since some time has passed; this is specifically for older .dcx archives which have been modified. Wulf's older tool for this broke DSMS, but not the game, as the game seemingly doesn't need the expanded size to extract, but Soulsformats does.

**Comment by Philiquaz** [comment]
Can someone with more knowhow confirm if this has any other impact than just the decompression step?
Is 0x100000 sufficient or sourced from somewhere? (perhaps game uses fixed buffer ahead of time to decompress?)
I'm happy to merge on the basis of just-werks, but there is a conversation about this going directly into dcx (and thus muddying the fact that the decompressedSize *should* be correct. Can we implement this fuzzy-sizing without impacting the actual dcx class?
Hesistantly I suggest our own MemoryStream wrapper which can handle creation of the backing array (and the fuzzing of its size, potentially on a toggle as per dcx assert-spoofing) without impacting the implicit documentation and semantics of dcx as given by the dcx implementation.

**Comment by Shadowth117** [comment]
0x100000 is 1mb and is just pulled out of aether here, was just something that worked and I mainly even made this PR on @kingborehaha 's suggestion since older tools did this. In the scheme of things, 1mb extra per unique archive is not horrific, especially nowadays.
Ideally, we could do this without considering the decompressedSize because the fact of the matter is the game doesn't care. Doesn't really need to be merged, but it's something that could help people wanting to mess about with Demon's Souls. Ideally as well, this wouldn't have ever been a thing, but it is what it is. Up to you if you want to get it in imo.

**Comment by Philiquaz** [comment]
Honestly I just assumed C# didn't even give that option lmao
My big meme about it was less about is it functional or reasonable, but just does it reflect the game and format and if not, is there a better way to tuck the problem away outside the format class.
If we can use decompressedSize just as "hey this is guideline" then I think we should do that.

**Comment by Shadowth117** [comment]
To me personally this seems reasonable, yeah. There's a lot of insanity with implementations and things, but it was always a funny point because these ones did work ingame. I definitely know people who would appreciate it getting merged though and I think you handled it reasonably. I hope others agree there.

**Pull request merged**
